name: smoke-ubuntu-linux

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: cpan Crypt::URandom
        run: sudo cpan Crypt::URandom
      - name: prove
        run: prove -l t

  linux:
    name: "linux ${{ matrix.perl-version }}"
    needs: [ubuntu]
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          [
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
#            "5.20",
#            "5.18",
#            "5.16",
#            "5.14",
          ]

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: cpan Crypt::URandom
        run: cpan Crypt::URandom
      - name: prove
        run: prove -l t

